# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android settings
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official

# Enable parallel builds and build caching
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
