-- =============================================================================
--  V1 — Schema inicial do Fast Trade
--
--  Equivale ao que o Hibernate gerava com ddl-auto: update, agora versionado.
--  A partir daqui o schema so muda por nova migration; o Hibernate roda em
--  modo `validate` e falha o boot se o codigo divergir do banco.
-- =============================================================================

-- ── USUARIOS ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    email           VARCHAR(255)   NOT NULL,
    password        VARCHAR(255)   NOT NULL,
    cpf_cnpj        VARCHAR(255),
    phone           VARCHAR(255),
    birth_date      VARCHAR(255),
    gender          VARCHAR(255),
    score           INTEGER,
    trades          INTEGER,
    blocked         BOOLEAN,
    address_street  VARCHAR(255),
    address_city    VARCHAR(255),
    address_state   VARCHAR(255),
    address_zip     VARCHAR(255),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS admin_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    CONSTRAINT uk_admin_users_email UNIQUE (email)
);

-- ── CATALOGO ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    slug  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS subcategories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    slug         VARCHAR(255),
    category_id  BIGINT,
    CONSTRAINT fk_subcategories_category
        FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    description     TEXT,
    price           NUMERIC(10, 2) NOT NULL,
    stock           INTEGER,
    is_active       BOOLEAN,
    image_url       TEXT,
    sku             VARCHAR(255),
    condition       VARCHAR(255),
    seller_id       BIGINT,
    category_id     BIGINT,
    subcategory_id  BIGINT,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT fk_products_seller
        FOREIGN KEY (seller_id) REFERENCES users (id),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_products_subcategory
        FOREIGN KEY (subcategory_id) REFERENCES subcategories (id)
);

-- ── CARRINHO ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS cart_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT  NOT NULL,
    product_id  BIGINT  NOT NULL,
    quantity    INTEGER NOT NULL,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    CONSTRAINT fk_cart_items_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    -- Um produto aparece uma unica vez por carrinho; a quantidade e um campo
    CONSTRAINT uk_cart_items_user_product UNIQUE (user_id, product_id)
);

-- ── PEDIDOS ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(255),
    user_id         BIGINT,
    user_name       VARCHAR(255),
    total           NUMERIC(10, 2),
    status          VARCHAR(255),
    payment_method  VARCHAR(255),
    status_note     VARCHAR(255),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uk_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL,
    product_id    BIGINT,
    product_name  VARCHAR(255),
    quantity      INTEGER,
    price         NUMERIC(10, 2),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (id)
);

-- ── FINANCEIRO ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS wallets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    user_name   VARCHAR(255),
    balance     NUMERIC(10, 2),
    updated_at  TIMESTAMP(6),
    CONSTRAINT uk_wallets_user UNIQUE (user_id),
    CONSTRAINT fk_wallets_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Nota: transactions.user_id e VARCHAR, nao FK — a entidade Transaction
-- declara `private String userId`. Mantido assim para nao quebrar o codigo;
-- normalizar isso seria uma migration futura.
CREATE TABLE IF NOT EXISTS transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         VARCHAR(255),
    user_name       VARCHAR(255),
    type            VARCHAR(255),
    status          VARCHAR(255),
    amount          NUMERIC(10, 2),
    description     VARCHAR(255),
    payment_method  VARCHAR(255),
    created_at      TIMESTAMP(6)
);

-- ── CHAT ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS chat_messages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room           VARCHAR(255)  NOT NULL,
    sender_id      BIGINT        NOT NULL,
    sender_name    VARCHAR(255)  NOT NULL,
    sender_role    VARCHAR(255)  NOT NULL,
    content        VARCHAR(2000) NOT NULL,
    type           VARCHAR(255)  NOT NULL,
    sent_at        TIMESTAMP(6)  NOT NULL,
    read_by_admin  BOOLEAN       NOT NULL
);

-- ── INDICES ─────────────────────────────────────────────────────────────────
-- FKs nao ganham indice automatico no PostgreSQL; sem eles, todo JOIN e todo
-- DELETE no lado pai vira sequential scan na tabela filha.

CREATE INDEX IF NOT EXISTS idx_subcategories_category  ON subcategories (category_id);
CREATE INDEX IF NOT EXISTS idx_products_category       ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_subcategory    ON products (subcategory_id);
CREATE INDEX IF NOT EXISTS idx_products_seller         ON products (seller_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user         ON cart_items (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_product      ON cart_items (product_id);
CREATE INDEX IF NOT EXISTS idx_orders_user             ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order       ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product     ON order_items (product_id);

-- Consultas frequentes do painel e do chat
CREATE INDEX IF NOT EXISTS idx_orders_status           ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at       ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_products_is_active      ON products (is_active);
CREATE INDEX IF NOT EXISTS idx_transactions_user       ON transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_room_sent ON chat_messages (room, sent_at);
