{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fast-trade.fullname" . }}
  labels:
    {{- include "fast-trade.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          # API REST
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "fast-trade.fullname" . }}-{{ .Values.backend.name }}
                port:
                  number: {{ .Values.backend.service.port }}
          # WebSocket STOMP/SockJS
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "fast-trade.fullname" . }}-{{ .Values.backend.name }}
                port:
                  number: {{ .Values.backend.service.port }}
          {{- end }}
          {{- if .Values.frontend.enabled }}
          # Painel Angular (catch-all, precisa vir por ultimo)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fast-trade.fullname" . }}-{{ .Values.frontend.name }}
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}
