{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fast-trade.fullname" . }}-db
  labels:
    {{- include "fast-trade.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ required "postgresql.auth.password e obrigatorio" .Values.postgresql.auth.password | quote }}
{{- end }}
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fast-trade.fullname" . }}-db
  labels:
    {{- include "fast-trade.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.externalDatabase.username | quote }}
  password: {{ required "externalDatabase.password e obrigatorio" .Values.externalDatabase.password | quote }}
{{- end }}
{{- if not .Values.jwt.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fast-trade.fullname" . }}-jwt
  labels:
    {{- include "fast-trade.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "jwt.secret e obrigatorio" .Values.jwt.secret | quote }}
  jwt-expiration: {{ .Values.jwt.expiration | quote }}
{{- end }}
